rvm: 2.3.1
script:
- bundle exec bin/rake db:create
- bundle exec bin/rake db:migrate
- bundle exec rspec spec

deploy:
  provider: s3
  access_key_id: AKIAJSBSR2YYJKKW5E6A
  secret_access_key:
    secure: j2SD87+ZLiuPfBG7CH+L2SLv4GAQ9BDXYuG/FTwci5tiF9Xyg+CftqCWGXI0Wj1bDor0cnUAeTsJpBY+YfSWOjvHXx1PAGsHlG6r1o5dnoUPeAl2B3gx4TOdgMvSEruaCacPfa8ThIQffWOXCtRu1l3YIQpyqwcWU/Uvok3CYC4R8XsubYYCRDyikl/SwzfbXmidbIaRZOqjMg/5ADDY2iNhZfIovoH5v/oAGVV03Q6y8lV5w7nUvZJ8YoAhXpkTAMQHN70Y9lwSdNFHSSDMf+yMbqMqfwuckMULN8HCTXmPp/lUWo3sUFcdMgQ9lKe/keriJUhYx5VeM9UousgIixa89LVezoEX5Q+A4Pnq0a4PJzcnflJstWkpZ9s50JLu+nly40G8RouIvIOUqr563+aQdh1xXBAbsdjRlOgdeK4Ug2oCp0+9+aqyJJB2PShmCgGG2WAD1e3h/JW/Xy2lpBetooFll9cCqTqPhM4rqPvgYqpRR7sTohAoMbs+Y4IjDet80lm0rH97CKRmqEL1gXcJgBXBPWY1yhhFF+lavO9rgVeiaSQGTpLOk8FVSuIl32N5oE3EUQOPh0PjWrYm+k8tYaeyrKx8XclaYu9iI6VgH7FdfDEsDsTpGT/zgGYKx5mtfm89vNmF7PgUq1kgF4cgcRtAEP+EgrM2L9dCQ1o=
  bucket: arukomp-instagram-dev
  region: eu-west-1
